version: '3.1'

services:
  cloud:
    image: nginx

  zookeeper:
    image: wurstmeister/zookeeper

  kafka:
    image: wurstmeister/kafka

  activemq:
    image: rmohr/activemq

  redis:
    image: redis

  mysql:
    image: mysql:5.7

  mongo:
    image: mongo
